// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybczibflpcttpzpoywti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliY3ppYmZscGN0dHB6cG95d3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzY4MjQsImV4cCI6MjA2NzYxMjgyNH0.Pn4nVzQaiBxRHO30n6EdbQ6eeWCR6ZXT6Ao1514zi1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});